import tkinter

win=tkinter.Tk()
win.title="Calculator"
win.minsize(500,400)
win.config(bg='black')

#name=tkinter.Entry()
#name.grid(row = 2, column = 1,padx=2,pady=3)

b1=tkinter.Button(text='9')
b1.grid(row=4,column=3)
b1=tkinter.Button(text='8')
b1.grid(row=4,column=2)
b1=tkinter.Button(text='7')
b1.grid(row=4,column=1)
b1=tkinter.Button(text='6')
b1.grid(row=5,column=3)
b1=tkinter.Button(text='5')
b1.grid(row=5,column=2)
b1=tkinter.Button(text='4')
b1.grid(row=5,column=1)
b1=tkinter.Button(text='3')
b1.grid(row=6,column=3)
b1=tkinter.Button(text='2')
b1.grid(row=6,column=2)
b1=tkinter.Button(text='1')
b1.grid(row=6,column=1)
b1=tkinter.Button(text='0')
b1.grid(row=7,column=1)
b1=tkinter.Button(text='.')
b1.grid(row=7,column=2)
b1=tkinter.Button(text='/')
b1.grid(row=7,column=3)
b1=tkinter.Button(text='=')
b1.grid(row=7,column=4)
b1=tkinter.Button(text='*')
b1.grid(row=6,column=4)
b1=tkinter.Button(text='+')
b1.grid(row=5,column=4)
b1=tkinter.Button(text=' -')
b1.grid(row=4,column=4)


win.mainloop()